name: "CD Staging Pipeline"
# This CD workflow triggers on direct push or aproved PR on the main branch.
# The if condition ensures that it does not run when PR is closed without approving.
# This CD Pipeline waits for CI to be successfully completed.

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy_staging:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    environment: staging
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (
        github.event.workflow_run.head_branch == 'main' || 
        (github.event.workflow_run.event == 'pull_request' && github.event.pull_request.merged == true)
      )
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to GCP VM
        env:
          HOSTNAME: ${{ secrets.GCP_VM_EXTERNAL_IP }}
          USERNAME: ${{ secrets.GCP_VM_USERNAME }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |    
          # Create SSH config file
          cat >> ~/.ssh/config << EOF
          Host gcp-vm
            HostName $HOSTNAME
            User $USERNAME
            IdentityFile $(pwd)/private_key
            StrictHostKeyChecking no
          EOF

          # SSH into the GCP VM and run deployment commands
          ssh gcp-vm '
            cd ${{ vars.APP_DIR }}
            git checkout main
            git pull

            echo "Logging into Docker Hub"
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            echo "Pulling the latest Docker images from Docker Hub"
            docker-compose -f docker-compose.prod.dockerhub.yaml pull

            echo "Starting the services with docker-compose"
            docker-compose -f docker-compose.prod.dockerhub.yaml up -d --build

            echo "Cleaning up unused Docker images"
            docker image prune -f
          '
          
          # Clean up sensitive files
          rm -f private_key