name: "CD Pipeline"
# This CD workflow triggers on manual workflow dispatch.

on:
  workflow_dispatch:

jobs:
  deploy_production:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.GCP_VM_EXTERNAL_IP }} >> ~/.ssh/known_hosts
      
      - name: Execute deployment script
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_EXTERNAL_IP }} "
              sudo -i && cd prod && \
              git checkout main && git pull && \
              if git diff --name-only HEAD~1 HEAD | grep -qE \"requirements\\.txt|Dockerfile|\\.sh\"; then \
                docker-compose up --build -d && \
                docker image prune -f; \
              fi
            "