name: "CD Pipeline"
# This CD workflow triggers on manual workflow dispatch.

on:
  workflow_dispatch:

jobs:
  deploy_production:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to GCP VM
        env:
          HOSTNAME: ${{ secrets.GCP_VM_EXTERNAL_IP }}
          USERNAME: ${{ secrets.GCP_VM_USERNAME }}
        run: |    
          # Create SSH config file
          cat >> ~/.ssh/config << EOF
          Host gcp-vm
            HostName $HOSTNAME
            User $USERNAME
            IdentityFile $(pwd)/private_key
            StrictHostKeyChecking no
          EOF

          # SSH into the GCP VM and run deployment commands
          ssh gcp-vm '
            sudo -i
            cd prod
            git checkout main
            git pull
            if git diff --name-only HEAD~1 HEAD | grep -qE "requirements\.txt|Dockerfile|\.sh"; then
              docker-compose up --build -d
              docker image prune -f
            fi
          '
          
          rm -f private_key